### ISSUE TITLE
harness container fails to run due to TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by jaehyeon-kim** [PacktPublishing/Building-Big-Data-Pipelines-with-Apache-Beam#38]
Hello, 

I tried to start the environment via `./env/start-all.sh`. 

First of all, I had to use an earlier version of kubernetes and I use v1.24.7.

The script completes without an error but I find the harness container in the flink task manager fails to run. 

```bash
$ k get po
NAME                                 READY   STATUS             RESTARTS        AGE
flink-jobmanager-7fcdd685cf-bxhtg    1/1     Running            0               19m
flink-taskmanager-85db6c9b98-9qlml   1/2     CrashLoopBackOff   8 (3m21s ago)   19m
kafka-0                              1/1     Running            3 (23m ago)     24m
packt-beam-7dc8c5b8df-kbnn8          1/1     Running            0               7m39s
zk-0                                 1/1     Running            0               24m
```

Here is the error.

```bash
2024/03/19 06:28:00 Starting worker pool 1: python -m apache_beam.runners.worker.worker_pool_main --service_port=50000 --container_executable=/opt/apache/beam/boot
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/site-packages/apache_beam/__init__.py", line 92, in <module>
    from apache_beam import coders
  File "/usr/local/lib/python3.7/site-packages/apache_beam/coders/__init__.py", line 17, in <module>
    from apache_beam.coders.coders import *
  File "/usr/local/lib/python3.7/site-packages/apache_beam/coders/coders.py", line 57, in <module>
    from apache_beam.coders import coder_impl
  File "apache_beam/coders/coder_impl.py", line 1, in init apache_beam.coders.coder_impl
  File "apache_beam/utils/windowed_value.py", line 39, in init apache_beam.utils.windowed_value
  File "/usr/local/lib/python3.7/site-packages/apache_beam/utils/timestamp.py", line 36, in <module>
    from apache_beam.portability import common_urns
  File "/usr/local/lib/python3.7/site-packages/apache_beam/portability/common_urns.py", line 22, in <module>
    from apache_beam.portability.api.beam_runner_api_pb2_urns import BeamConstants
  File "/usr/local/lib/python3.7/site-packages/apache_beam/portability/api/beam_runner_api_pb2_urns.py", line 2, in <module>
    from . import metrics_pb2
  File "/usr/local/lib/python3.7/site-packages/apache_beam/portability/api/metrics_pb2.py", line 15, in <module>
    from . import beam_runner_api_pb2 as beam__runner__api__pb2
  File "/usr/local/lib/python3.7/site-packages/apache_beam/portability/api/beam_runner_api_pb2.py", line 15, in <module>
    from . import endpoints_pb2 as endpoints__pb2
  File "/usr/local/lib/python3.7/site-packages/apache_beam/portability/api/endpoints_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
2024/03/19 06:28:00 Python SDK worker pool exited: exit status 1
```

It might be related to the following docker file in `env/docker/harness/Dockerfile`.

```Dockerfile
FROM apache/beam_python3.7_sdk:2.33.0

RUN apt -y update && apt -y install python3-protobuf && python3 -m pip install --upgrade pip && python3 -m pip install grpcio grpcio-tools
```

Can you please inform me how to fix the error?

Cheers,
Jaehyeon

**Comment by Arbegas** [comment]
uninstalling protobuf in \env\docker\harness\Dockerfile after execute install protobuf again. !worked for me!!
***********************************************
FROM apache/beam_python3.7_sdk:2.33.0


RUN apt -y update
RUN python3 -m pip uninstall -y six
RUN python3 -m pip uninstall -y protobuf
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install python3-protobuf
RUN python3 -m pip install six==1.15.0 
RUN python3 -m pip install grpcio==1.34.0 grpcio-tools

**Comment by jaehyeon-kim** [comment]
Hi @Arbegas 

Thanks for your update. 

Running the examples in Kubernetes is too much for me, and I ended up creating a local environment separately. I'm writing a series of posts that include most of the examples in the book. Here is the link [Apache Beam Python Examples](https://jaehyeon.me/blog/2024-07-04-beam-examples-1/).
